#!/nix/store/9ywr69qi622lrmx5nn88gk8jpmihy0dz-bash-4.4-p23/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


picom &

setxkbmap -layout "us,ir" -option "grp:alt_shift_toggle" &

##################################
killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar mybar &
##################################

feh --bg-fill $HOME/wp/red* &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#b0151f"
bspc config normal_border_color "#212121"
bspc config active_border_color "#b0151f"
bspc config presel_feedback_color "#b0151f"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
